#!/usr/bin/env bash

LOG_FILE=grunt.log
count=`git status -s | awk '{print $1}' | grep 'A\|M' | wc -l | sed -e 's/^[ \t]*//'`
if [ $count != 0 ]; then
    echo "Validating changed files..."
    grunt gitnewer:eslint > $LOG_FILE
    result=`tail -1 $LOG_FILE`
    if [ "$result" == "Aborted due to warnings." ]; then
      cat $LOG_FILE
      exit 1;
    fi
    npm test
    result=$?
    exit $result 
fi

