#!/usr/bin/env python

import argparse, os, subprocess, sys

def main():
  name = 'WebIDL Binder'
  parser = argparse.ArgumentParser(description=('Call %s' % name))
  parser.add_argument('-v', '--verbose', action='store_true',
    help='If set, print message from %s' % name)
  parser.add_argument('-d', '--debug', action='store_true',
    help='If set, make binding codes in debug version')
  parser.add_argument('idl', help='IDL file for generating binding code')
  args = parser.parse_args()

  if args.verbose:
    os.putenv('IDL_VERBOSE', '1')
  os.putenv('IDL_CHECKS', 'ALL' if args.debug else 'FAST')

  cur_path = os.path.abspath(os.path.dirname(__file__))
  bin_path = os.path.join(cur_path, 'webidl_binder.py')
  glue_path = os.path.join(os.path.dirname(args.idl), 'glue')
  print bin_path
  sys.exit(subprocess.call(['python', bin_path, args.idl, glue_path]))

if __name__ == '__main__':
  main()
