#%RAML 0.8
title: OCFDoor
version: v1.1.0-20160519
traits:
 - interface :
     queryParameters:
       if:
         enum: ["oic.if.a", "oic.if.baseline"]

/DoorResURI:
  description: |
    This resource describes a door.
    A door is modelled by means of
      openState (Open/Closed).
      openDuration (ISO 8601 Time).
      openAlarm (boolean).
    For openState, the value 'Open' indicates the door is open.
    The value 'Closed' indicates the door is closed.
    The type of openDuration is an ISO 8601 Time encoded string.
    The openAlarm value 'true' indicates that the open alarm is active.
    The openAlarm value 'false' indicates that open alarm is not active.

  displayName: Door
  
  is : ['interface']
  get:
    description: |
      retrieves the state of the Door.

    responses :
      200:
        body:
          application/json:
            schema: |
              {
                "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.door.json#",
                "$schema": "http://json-schema.org/draft-04/schema#",
                "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
                "title": "Door",
                "definitions": {
                  "oic.r.door": {
                    "type": "object",
                    "properties": {
                      "openState" : {
                        "enum": ["Open","Closed"],
                        "description": "ReadOnly, The state of the door (open or closed)"
                      }
                    }
                  }
                },
                "type": "object",
                "allOf": [
                  {"$ref": "oic.core.json#/definitions/oic.core"},
                  {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
                  {"$ref": "#/definitions/oic.r.door"}
                ],
                "required": ["openState"]
              }

            example: |
              {
                "rt" :          ["oic.r.door"],
                "id":           "unique_example_id",
                "openState":    "Open"
              }

  post:
    description: |
      Sets the current Door properties.
      The only property that can be set as part of an update operation is
        the openAlarm.
      This can be made active (true) or inactive (false)

    body:
      application/json:
        schema: |
          {
            "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.door-Update.json#",
            "$schema": "http://json-schema.org/draft-04/schema#",
            "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
            "title": "Door",
            "definitions": {
              "oic.r.door": {
                "type": "object",
                "properties": {
                  "openAlarm": {
                    "type": "boolean",
                    "description": "The state of the door open alarm"
                  }
                }
              }
            },
            "type": "object",
            "allOf": [
              {"$ref": "oic.core.json#/definitions/oic.core"},
              {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
              {"$ref": "#/definitions/oic.r.door"}
            ]
          }

        example: |
          {
            "id":         "unique_example_id",
            "openAlarm":  false
          }

    responses :
      200:
        body:
          application/json:
            schema: |
              {
                "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.door-Update.json#",
                "$schema": "http://json-schema.org/draft-04/schema#",
                "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
                "title": "Door",
                "definitions": {
                  "oic.r.door": {
                    "type": "object",
                    "properties": {
                      "openAlarm": {
                        "type": "boolean",
                        "description": "The state of the door open alarm"
                      }
                    }
                  }
                },
                "type": "object",
                "allOf": [
                  {"$ref": "oic.core.json#/definitions/oic.core"},
                  {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
                  {"$ref": "#/definitions/oic.r.door"}
                ]
              }

            example: |
              {
                "id":         "unique_example_id",
                "openAlarm":  false
              }
