#%RAML 0.8
title: OCFMediaSourceList
version: v1.1.0-20160519
traits:
 - interface :
     queryParameters:
       if:
         enum: ["oic.if.a", "oic.if.baseline"]

/mediaSourceListResURI:
  description: |
    This resource provides the list of media sources available on the device.
    The sources are an array of mediaSource(s) as separately defined.
    The basic resource type oic.r.media.input does not provide any indications whether the source is input or output.
    Hence, two specializations of this resource exist.
    When a device exposes input sources then an instance of this resource with a resource type of oic.r.media.input is exposed.
    When a device exposes output sources then an instance of this resource with a resource type of oic.r.media.output is exposed.
    A device that exposes both input and output media sources then exposes two instances of this resource,
    one with a resource type or oic.r.media.input and one with a resource type of oic.r.media.output

  displayName: Media Source List

  is : ['interface']
  get:
    responses :
      200:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
                "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.media.input.json#",
                "title": "Media Source List",
                "definitions": {
                  "oic.r.media.input": {
                    "properties": {
                      "sources": {
                        "type": "array",
                        "items": {
                          "oneOf": [
                            { "$ref": "oic.r.mediaSource.json#" }
                          ]
                        }
                      }
                    }
                  }
                },
                "type": "object",
                "allOf": [
                  { "$ref": "oic.core.json#/definitions/oic.core"},
                  { "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
                  { "$ref": "#/definitions/oic.r.media.input"}
                ],
                "required": ["sources"]
              }

            example: |
              {
                "rt": ["oic.r.media.input"],
                "id": "unique_example_id",
                "sources": [
                  {
                    "sourceName": "HDMI-CEC",
                    "sourceNumber": "1",
                    "sourceType": "audioPlusVideo",
                    "status": true
                  },
                  {
                    "sourceName": "dualRCA",
                    "sourceNumber": "1",
                    "sourceType": "audioOnly",
                    "status": false
                  }
                ]
              }

  post:
    description: |
      Changes the status of the source(s).
      Allows changes of the sourceName and the status.

    body:
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
            "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.media.input.json#",
            "title": "Media Source List",
            "definitions": {
              "oic.r.media.input": {
                "properties": {
                  "sources": {
                    "type": "array",
                    "items": {
                      "oneOf": [
                        { "$ref": "oic.r.mediaSource.json#" }
                      ]
                    }
                  }
                }
              }
            },
            "type": "object",
            "allOf": [
              { "$ref": "oic.core.json#/definitions/oic.core"},
              { "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
              { "$ref": "#/definitions/oic.r.media.input"}
            ],
            "required": ["sources"]
          }

        example: |
          {
            "id":     "unique_example_id",
            "sources": [
              {
               "sourceName":    "my new name",
               "sourceNumber":  "1",
               "status":        true
              }
            ]
          }

    responses :
      200:
        body:
          application/json:
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
                "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.media.input.json#",
                "title": "Media Source List",
                "definitions": {
                  "oic.r.media.input": {
                    "properties": {
                      "sources": {
                        "type": "array",
                        "items": {
                          "oneOf": [
                            { "$ref": "oic.r.mediaSource.json#" }
                          ]
                        }
                      }
                    }
                  }
                },
                "type": "object",
                "allOf": [
                  { "$ref": "oic.core.json#/definitions/oic.core"},
                  { "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
                  { "$ref": "#/definitions/oic.r.media.input"}
                ],
                "required": ["sources"]
              }

            example: |
              {
                "id":     "unique_example_id",
                "sources": [
                  {
                    "sourceName":   "my new name",
                    "sourceNumber": "1",
                    "status":       true
                  }
                ]
              }
