#%RAML 0.8
title: OCFAirFlow
version: v1.1.0-20160519
traits:
 - interface :
     queryParameters:
       if:
         enum: ["oic.if.a", "oic.if.baseline"]

/AirFlowResURI:
  description: |
    This resource describes the properties associated with air flow.
    The direction is the directionality of the air flow if applicable.
    Direction values are dependent on the capabilities of the unit.
    The speed is an integer representing the current speed level for the unit.
    The range is an array of the min,max values for the speed level.

  displayName: Air flow

  is : ['interface']
  get:
    description: |
      Retrieves the current air flow values.

    responses :
      200:
        body:
          application/json:
            schema: |
              {
                "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.airFlow.json#",
                "$schema": "http://json-schema.org/draft-04/schema#",
                "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
                "title": "Air Flow",
                "definitions": {
                  "oic.r.airflow": {
                    "type": "object",
                    "properties": {
                      "direction": {
                        "type": "string",
                        "description": "Directionality of the air flow",
                        "default": "Off"
                      },
                      "speed": {
                        "type": "integer",
                        "description": "Current speed level",
                        "default": 0
                      },
                      "range": {
                        "type": "array",
                        "description": "ReadOnly, Min,max values for the speed level",
                        "items": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                },
                "type": "object",
                "allOf": [
                  {"$ref": "oic.core.json#/definitions/oic.core"},
                  {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
                  {"$ref": "#/definitions/oic.r.airflow"}
                ],
                "required": ["speed"]
              }

            example: |
              {
                "rt":         ["oic.r.airflow"],
                "id":         "unique_example_id",
                "direction":  "left",
                "speed":      5,
                "range":      [1,7]
              }

  post:
    description: |
      Sets the current air flow values.
      Only direction and speed may be set by an update operation.

    body:
      application/json:
        schema: |
          {
            "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.airFlow.json#",
            "$schema": "http://json-schema.org/draft-04/schema#",
            "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
            "title": "Air Flow",
            "definitions": {
              "oic.r.airflow": {
                "type": "object",
                "properties": {
                  "direction": {
                    "type": "string",
                    "description": "Directionality of the air flow",
                    "default": "Off"
                  },
                  "speed": {
                    "type": "integer",
                    "description": "Current speed level",
                    "default": 0
                  },
                  "range": {
                    "type": "array",
                    "description": "ReadOnly, Min,max values for the speed level",
                    "items": {
                      "type": "integer"
                    }
                  }
                }
              }
            },
            "type": "object",
            "allOf": [
              {"$ref": "oic.core.json#/definitions/oic.core"},
              {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
              {"$ref": "#/definitions/oic.r.airflow"}
            ],
            "required": ["speed"]
          }

        example: |
          {
            "id":         "unique_example_id",
            "direction":  "right",
            "speed":      3
          }

    responses :
      200:
        body:
          application/json:
            schema: |
              {
                "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.airFlow.json#",
                "$schema": "http://json-schema.org/draft-04/schema#",
                "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
                "title": "Air Flow",
                "definitions": {
                  "oic.r.airflow": {
                    "type": "object",
                    "properties": {
                      "direction": {
                        "type": "string",
                        "description": "Directionality of the air flow",
                        "default": "Off"
                      },
                      "speed": {
                        "type": "integer",
                        "description": "Current speed level",
                        "default": 0
                      },
                      "range": {
                        "type": "array",
                        "description": "ReadOnly, Min,max values for the speed level",
                        "items": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                },
                "type": "object",
                "allOf": [
                  {"$ref": "oic.core.json#/definitions/oic.core"},
                  {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
                  {"$ref": "#/definitions/oic.r.airflow"}
                ],
                "required": ["speed"]
              }

            example: |
              {
                "id":         "unique_example_id",
                "direction":  "right",
                "speed":      3
              }

      403:
        description: |
          This response is generated by the OCF Server when the client sends:
            An update with an invalid property value for direction.
            An update with an out of range property value for speed.
          The server responds with the current resource representation.

        body:
          application/json:
            schema: |
              {
                "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.airFlow.json#",
                "$schema": "http://json-schema.org/draft-04/schema#",
                "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
                "title": "Air Flow",
                "definitions": {
                  "oic.r.airflow": {
                    "type": "object",
                    "properties": {
                      "direction": {
                        "type": "string",
                        "description": "Directionality of the air flow",
                        "default": "Off"
                      },
                      "speed": {
                        "type": "integer",
                        "description": "Current speed level",
                        "default": 0
                      },
                      "range": {
                        "type": "array",
                        "description": "ReadOnly, Min,max values for the speed level",
                        "items": {
                          "type": "integer"
                        }
                      }
                    }
                  }
                },
                "type": "object",
                "allOf": [
                  {"$ref": "oic.core.json#/definitions/oic.core"},
                  {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
                  {"$ref": "#/definitions/oic.r.airflow"}
                ],
                "required": ["speed"]
              }

            example: |
              {
                "id":         "unique_example_id",
                "direction":  "right",
                "speed":      3
              }
