#%RAML 0.8
title: OICSleepSensor
version: v1.1.0-20160519
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.s","oic.if.baseline"]

/SleepSensorResURI:
  description: |
    This resource describes whether human sleep has been sensed or not.
    The value is a boolean.
    A value of 'true' means that sleep has been sensed.
    A value of 'false' means that sleep not been sensed.

  displayName: Sleep Sensor
  is: [ interface ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "id": "http://openinterconnect.org/iotdatamodels/schemas/oic.r.sensor.sleep.json#",
                "$schema": "http://json-schema.org/draft-04/schema#",
                "description" : "Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.",
                "title": "Sleep Sensor",
                "definitions": {
                  "oic.r.sensor.sleep": {
                    "type": "object",
                    "properties": {
                      "sleep": {
                        "type": "boolean",
                        "description": "Status of Sleep"
                      }
                    }
                  }
                },
                "type": "object",
                "allOf": [
                  {"$ref": "oic.core.json#/definitions/oic.core"},
                  {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
                  {"$ref": "#/definitions/oic.r.sensor.sleep"}
                ],
                "required": [ "sleep" ]
              }
              
            example: |
              {
                "rt":     ["oic.r.sensor.sleep"],
                "id":     "unique_example_id",
                "value":  true
              }