#%RAML 0.8
title: WWST Sound Pressure Level
version: v1.0.0-20180726
schemas:
- SoundPressureLevel: |
    {
        "id": "http://www.samsung.com/schemas/x.com.st.soundPressureLevel.json#",
        "$schema": "http://json-schema.org/draft-04/schema#",
        "description" : "Copyright (c) 2016, 2017, 2018 Open Connectivity Foundation, Inc. All rights reserved.",
        "definitions": {
            "x.com.st.soundPressureLevel": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "number",
                        "description": "The level of sound pressure level detected",
                        "minimum": 0,
                        "maximum": 194
                    },
                    "unit": {
                        "type": "string",
                        "enum": ["dB"],
                        "description": "The unit of sound pressure level detected"
                    }
                }
            }
        },
        "type": "object",
        "allOf": [
            {
                "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
            },
            {
                "$ref": "#/definitions/x.com.st.soundPressureLevel"
            }
        ],
        "required": [
            "value"
        ]
    }

traits:
    - interface:
        queryParameters:
            if:
                enum: ["oic.if.s","oic.if.baseline"]

/WWSTSoundPressureLevewlResURI:
    description: |
        The level of sound pressure
    displayName: WWST Sound Pressure Level
    is: [ interface ]

    get:
        description: |
            Retrieves the level of sound pressure
        responses:
            200:
                body:
                    application/json:
                        schema: SoundPressureLevel
                        example: |
                            {
                                "rt": ["x.com.st.soundPressureLevel"],
                                "id": "unique_example_id",
                                "value": 50,
                                "unit": "dB"
                            }