#%RAML 0.8
title: STButton
version: v1.1.1-20180625
schemas:
- Button: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.button.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description" : "Copyright (c) 2016, SmartThings. All rights reserved.",
      "title": "STButton",
      "definitions": {
        "x.com.st.button": {
            "properties": {
              "button": {
                "type": "string",
                "enum": ["Ready", "double", "held", "pushed"],
                "description": "Status of the button"
              },
              "numberOfButtons": {
                  "type": "number",
                  "description": "The number of buttons on the device"
              }
            }
        }
      },
      "type": "object",
      "allOf": [
        {"$ref": "oic.core.json#/definitions/oic.core"},
        {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
        {"$ref": "#/definitions/x.com.st.button"}
      ],
      "required": ["button"]
    }
traits:
 - interface :
     queryParameters:
       if:
         enum: ["oic.if.baseline","oic.if.s"]

/button:
  displayName: Button
  description: |
    This resource implements button capability from SmartThings.

  is : ['interface']

  get:
    description: |
      Retrieves the current status of button.

    responses :
      200:
        body:
          application/json:
            schema: Button
            example: |
              {
                "id": "unique_example_id",
                "button": "pushed",
                "numberOfButtons": 3
              }
