#%RAML 0.8
title: ST Window Shade
version: v1.1.0-20180130
schemas:
- WindowShadeGet: |
    {
      "id": "http://samsung.com/schemas/x.com.st.windowshade.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description" : "Copyright (c) 2016 Samsung Electronics, Inc. All rights reserved.",
      "title": "ST Window Shade",
      "definitions": {
        "x.com.st.windowshade": {
          "type": "object",
          "properties": {
            "windowShade": {
              "type": "string",
              "enum": ["unknown", "open", "closing", "closed", "opening", "partially open"],
              "description":"Status of the window shade"
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {"$ref": "oic.core.json#/definitions/oic.core"},
        {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
        {"$ref": "#/definitions/x.com.st.windowshade"}
      ],
      "required": ["windowShade"]
    }
- WindowShadePost: |
    {
      "id": "http://samsung.com/schemas/x.com.st.windowshade.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description" : "Copyright (c) 2016 Samsung Electronics, Inc. All rights reserved.",
      "title": "ST Window Shade",
      "definitions": {
        "x.com.st.windowshade": {
          "type": "object",
          "properties": {
            "windowShade": {
              "type": "string",
              "enum": ["open", "closing", "closed", "opening", "presetPosition"],
              "description":"Status of the windowShade"
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {"$ref": "oic.core.json#/definitions/oic.core"},
        {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
        {"$ref": "#/definitions/x.com.st.windowshade"}
      ],
      "required": ["windowShade"]
    }
- Exception: |
    {
      "id": "http://samsung.com/iotdatamodels/schemas/stocfexception.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016 Samsung, Inc. All rights reserved.",
      "title": "StOcfException",
      "definition": {
        "stOcfError": {
        "type": "object",
          "properties": {
            "code": {
              "type": "string",
              "enum": ["OCF_001", "OCF_005"],
              "description": "Code of the exception"
            },
            "message": {
              "type": "string",
              "description": "Message of the exception"
            }
          }
        }
      }
    }
traits:
 - interface :
     queryParameters:
       if:
         enum: ["oic.if.baseline"]

/WindowShade:
  displayName: WindowShade
  description: |
    This resource implements Window Shade capability from SmartThings.

  is : ['interface']
  get:
    description: |
      Retrieve the current state and operation of the window shade.

    responses :
      200:
        body:
          application/json:
            schema: WindowShadeGet
            example: |
              {
                  "id": "unique_example_id",
                  "windowShade":	"closing"
              }

  post:
    description: |
      Update the current status of the window shade.
      Posting "opening" or "open" in the "closed" or "closing" state will transit
      the state to "opening". The "opening" state will last for 10 - 20 seconds
      until the window shade is completely open. Posting "closing" or "closed"
      in the "open" or "closed" state will transit the state to "closing". The
      "closing" state will last for 10 - 20 seconds until the window shade is
      completely closed.

    body:
      application/json:
        schema: WindowShadePost
        example: |
          {
            "id": "unique_example_id",
            "windowShade":	"closing"
          }
    responses :
      200:
        body:
          application/json:
            schema: WindowShadePost
            example: |
              {
                "id":    "unique_example_id",
                "windowShade":"closing"
              }
