#%RAML 0.8
title: STMomentary
version: v0.0.1-20180607
schemas:
- Push: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.momentary.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016 Samsung Electronics, Inc. All rights reserved.",
      "title": "Smart Things Momentary",
      "definitions": {
        "x.com.st.momentary": {
          "type": "object",
          "properties": {
              "button": {
              "type": "string",
              "enum": ["pushed"],
              "description": "Push the momentary switch"
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.core.json#/definitions/oic.core"
        },
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
        },
        {
          "$ref": "#/definitions/x.com.st.momentary"
        }
      ],
      "required": ["button"]
    }
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline", "x.com.st.if.temporary"]

/momentary:
  description: |
        This resource allows for the control of a momentary switch device
  displayName: WWST momentary
  is: [ interface ]
  post:
    description: |
      Push the momentary switch.
    body:
      application/json:
        schema: Push
        example: |
          {
            "id":    "unique_id",
            "button":"pushed"
          }
    responses:
      200:
        body:
          application/json:
            schema: Push
            example: |
              {
                "rt": ["x.com.st.momentary"],
                "id": "unique_example_id",
                "button":"pushed"
              }
