#%RAML 0.8
title: WWST Oven mode
version: v1.0.0-20170911
schemas:
- Mode: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.mode.oven.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016, 2017 Open Connectivity Foundation, Inc. All rights reserved.",
      "title": "WWST Mode",
      "definitions": {
        "x.com.st.mode.oven": {
          "type": "object",
          "properties": {
            "supportedModes": {
              "type": "array",
              "readOnly": true,
              "description": "Array of possible modes the device supports.",
              "items": {
                "type": "string"
              }
            },
            "modes": {
              "type": "array",
              "description": "Array of the currently active mode(s)",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
        },
        {
          "$ref": "#/definitions/x.com.st.mode.oven"
        }
      ],
      "required": [
        "supportedModes",
        "modes"
      ]
    }
- ModeUpdate: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.mode.oven.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016, 2017 Open Connectivity Foundation, Inc. All rights reserved.",
      "title": "WWST Mode Update",
      "definitions": {
        "x.com.st.mode.oven": {
          "type": "object",
          "properties": {
            "modes": {
              "type": "array",
              "description": "Desired mode",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
        },
        {
          "$ref": "#/definitions/x.com.st.mode.oven"
        }
      ],
      "required": [
        "modes"
      ]
    }

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a","oic.if.s","oic.if.baseline"]

/WWSTOvenmodeResURI:
  description: |
        Oven mode
  displayName: WWST Oven mode
  is: [ interface ]

  get:
    description: |
      Retrieves the current Oven mode
    responses:
      200:
        body:
          application/json:
            schema: Mode
            example: |
              {
                "rt":             ["x.com.st.mode.oven"],
                "id":             "unique_example_id",
                "modes": [ "heating" ],
                "supportedModes": ["heating", "grill", "warming", "defrosting"]
              }

  post:
    description: |
      Sets the desired Oven mode
    body:
      application/json:
        schema: ModeUpdate
        example: |
          {
            "id":    "unique_example_id",
            "modes": ["heating"]
          }
    responses:
      200:
        body:
          application/json:
            schema: ModeUpdate
            example: |
              {
                "id":    "unique_example_id",
                "modes": ["heating"]
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an value for mode that is not found in supportedModes.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: Mode
            example: |
              {
                "id":             "unique_example_id",
                "modes": [ "heating" ],
                "supportedModes": ["heating", "grill", "warming", "defrosting"]
              }
