#%RAML 0.8
title: STsoundsensor
version: v1.1.1-20161122
schemas:
- soundsensor: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.soundsensor.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016, SmartThings. All rights reserved.",
      "title": "soundsensor ",
      "definitions": {
        "x.com.st.soundsensor": {
          "allOf": [
            {"$ref": "oic.r.sensor.json#/definitions/oic.r.sensor"}
          ]
        }
      },
      "type": "object",
      "allOf": [
        {"$ref": "oic.core.json#/definitions/oic.core"},
        {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
        {"$ref": "#/definitions/x.com.st.soundsensor"}
      ],
      "required": [
        "value"
      ]
    }
traits:
 - interface :
     queryParameters:
       if:
         enum: ["oic.if.baseline"]
/soundSensor:
  displayName: soundSensor
  description: |
    This resource implements soundsensor  capability from SmartThings.Value is boolean.
  is : ['interface']

  get:
    description: |
      detects the status of soundsensor
    responses :
      200:
        body:
          application/json:
            schema: soundsensor
            example: |
              {
                "rt":    ["x.com.st.soundsensor"],
                "id": "unique_example_id",
                "value": "true"
              }
