#%RAML 0.8
title: STTone
version: v1.1.1-20161122
schemas:
- Tone: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.tone.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016 Samsung Electronics, Inc. All rights reserved.",
      "title": "Smart Things Tone",
      "definitions": {
        "x.com.st.tone": {
          "type": "object",
          "properties": {
              "toneValue": {
                "type": "boolean",
                "description": "Play beep"
              }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.core.json#/definitions/oic.core"
        },
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
        },
        {
          "$ref": "#/definitions/x.com.st.tone"
        }
      ],
      "required": ["toneValue"]
    }
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

/tone:
    description: |
          This resource specifies the tone value as true to indicate to beep
    displayName: WWST tone
    is: [ interface ]
    post:
      description: |
          Sets the desired Tone beep.
      body:
        application/json:
          schema: Tone
          example: |
            {
              "id":             "unique_id",
              "toneValue":  true
            }
      responses:
        200:
          description: |
            Indicates that the Tone beep was changed.
            The beep status is provided in the response.
          body:
            application/json:
              schema: Tone
              example: |
                {
                  "id":             "unique_id",
                  "toneValue":  true
                }
