#%RAML 0.8
title: STEnergyeter
version: v1.1.1-20161122
schemas:
- Consumption: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.energymeter.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Energy Meter",
      "definitions": {
        "x.com.st.energymeter": {
          "properties": {
            "energy": {
              "type": "number",
              "description": "ReadOnly, Energy consumed"
            },
            "unit": {
              "type": "string",
              "enum": [
                "Wh",
                "kWh",
                "mWh"
              ],
              "description": "The current state of unit"
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.core.json#/definitions/oic.core"
        },
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseResource"
        },
        {
          "$ref": "#/definitions/x.com.st.energymeter"
        }
      ],
      "required": [
        "energy",
        "unit"
      ]
    }
traits:
- interface:
    queryParameters:
     if:
          enum: ["oic.if.baseline","oic.if.s"]
/EnergyMeter:
  description: This resource describes the energy consumed by the device as reported by the Energy meter.
  displayName: Energy Meter
  is: [ interface ]
  get:
    description: |
      Provides the current Energy consumption reported by meter.
    responses:
      200:
        body:
          application/json:
            schema: Consumption
            example: |
              {
                "rt":     "x.com.st.energymeter",
                "id":     "unique_example_id",
                "energy":  2000,
                "unit": "Wh"
              }
