#%RAML 0.8
title: ST Notification
version: v1.1.0-20180803
schemas:
- Notification: |
    {
      "id": "http://samsung.com/schemas/x.com.st.notification.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description" : "Copyright (c) 2016, 2017, 2018 Samsung Electronics, Inc. All rights reserved.",
      "title": "ST Notification",
      "definitions": {
        "x.com.st.notification": {
          "type": "object",
          "properties": {
            "notification": {
              "type": "string",
              "description":"The notification message to be displayed on the device"
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {"$ref": "oic.core.json#/definitions/oic.core"},
        {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
        {"$ref": "#/definitions/x.com.st.notification"}
      ],
      "required": ["notification"]
    }
traits:
  - interface:
      queryParameters:
        if:
          enum: ["x.com.st.if.temporary","oic.if.baseline"]

/WWSTNotificationResURI:
  description: |
        Allows for displaying notifications on devices that allow notifications to be displayed
  displayName: WWST Notification
  is: [ interface ]
  post:
    description: |
      Post displaying notifications to device.
    body:
      application/json:
        schema: Notification
        example: |
          {
            "id": "unique_example_id",
            "notification" : "This is the sample notification"
          }
    responses:
      200:
        body:
          application/json:
            schema: Notification
            example: |
              {
                "rt": ["x.com.st.notification"],
                "id": "unique_example_id",
                "notification" : "This is the sample notification"
              }
