#%RAML 0.8
title: STRefresh
version: v1.0.0-20180803
schemas:
- Refresh: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.refresh.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016, 2017, 2018 Samsung Electronics, Inc. All rights reserved.",
      "title": "WWST Refresh",
      "definitions": {
        "x.com.st.refresh": {
          "type": "object",
          "properties": {
            "refresh": {
              "type": "string",
              "enum": ["refreshed"],
              "description": "Send the refresh command to the device"
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.core.json#/definitions/oic.core"
        },
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
        },
        {
          "$ref": "#/definitions/x.com.st.refresh"
        }
      ],
      "required": ["refresh"]
    }
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline", "x.com.st.if.temporary"]

/Refresh:
  description: |
        Allow the execution of the refresh command for devices that support it
  displayName: WWST refresh
  is: [ interface ]
  post:
    description: |
      Send the refresh command to the device
    body:
      application/json:
        schema: Refresh
        example: |
          {
            "id":    "unique_id",
            "refresh":"refreshed"
          }
    responses:
      200:
        body:
          application/json:
            schema: Refresh
            example: |
              {
                "rt": ["x.com.st.refresh"],
                "id": "unique_example_id",
                "refresh":"refreshed"
              }
