#%RAML 0.8
title: WWST Equivalent Cabon Dioxide Measurement
version: v1.0.0-20180815
schemas:
- EquivalentCarbonDioxide: |
    {
        "id": "http://www.samsung.com/schemas/x.com.st.equivalentCarbonDioxideMeasurement.json#",
        "$schema": "http://json-schema.org/draft-04/schema#",
        "description" : "Copyright (c) 2016, 2017, 2018 Open Connectivity Foundation, Inc. All rights reserved.",
        "definitions": {
            "x.com.st.equivalentCarbonDioxideMeasurement": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "integer",
                        "description": "The equivalent carbon dioxide level detected in ppm by volume",
                        "minimum": 0,
                        "maximum": 1000000
                    },
                    "unit": {
                        "type": "string",
                        "enum": ["ppm"],
                        "description": "The unit of equivalent carbon dioxide detected"
                    }
                }
            }
        },
        "type": "object",
        "allOf": [
            {
                "$ref": "oic.core.json#/definitions/oic.core"
            },
            {
                "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
            },
            {
                "$ref": "#/definitions/x.com.st.equivalentCarbonDioxideMeasurement"
            }
        ],
        "required": [
            "value",
            "unit"
        ]
    }

traits:
    - interface:
        queryParameters:
            if:
                enum: ["oic.if.s","oic.if.baseline"]

/WWSTEquivalentCarbonDioxideMeasurementResURI:
    description: |
        The level of carbon dioxide detected
    displayName: WWST Equivalent Cabon Dioxide Measurement
    is: [ interface ]

    get:
        description: |
            Measure equivalent carbon dioxide levels
        responses:
            200:
                body:
                    application/json:
                        schema: EquivalentCarbonDioxide
                        example: |
                            {
                                "rt": ["x.com.st.equivalentCarbonDioxideMeasurement"],
                                "id": "unique_example_id",
                                "value": 50,
                                "unit": "ppm"
                            }