#%RAML 0.8
title: STTamperAlert
version: v1.1.1-20180702
schemas:
- TamperAlert: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.tamperalert.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description" : "Copyright (c) 2016, SmartThings. All rights reserved.",
      "title": "STTamperAlert",
      "definitions": {
        "x.com.st.tamperalert": {
          "properties": {
            "value": {
              "type": "boolean",
              "description": "Status of the tamper alert"
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {"$ref": "oic.core.json#/definitions/oic.core"},
        {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
        {"$ref": "#/definitions/x.com.st.tamperalert"}
      ],
      "required": ["value"]
    }
traits:
 - interface :
     queryParameters:
       if:
         enum: ["oic.if.baseline","oic.if.s"]

/tamperalert:
  displayName: Tamper Alert
  description: |
    This resource implements tamper alert capability from SmartThings.

  is : ['interface']

  get:
    description: |
      Retrieves the current status of tamper alert.

    responses :
      200:
        body:
          application/json:
            schema: TamperAlert
            example: |
              {
                "id": "unique_example_id",
                "value": true
              }
