#%RAML 0.8
title: WWST Media Preset
version: v1.0.0-20180821
schemas:
- Presets: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.mediaPreset.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description" : "Copyright (c) 2016, 2017, 2018 SmartThings. All rights reserved.",
      "title": "WWST Media Preset",
      "definitions": {
        "x.com.st.mediaPreset": {
          "type": "object",
          "properties": {            
            "presets": {
              "type": "array",
              "description": "All the presets for the player",
              "items": {
                "type": "object", 
                "properties": { 
                  "id": { 
                    "type": "string", 
                    "description": "Id of the preset" 
                  }, 
                  "name": { 
                    "type": "string", 
                    "description": "Name of the preset" 
                  } 
                }
              }
            }
          }
        }
      },    
      "type": "object",
      "allOf": [
        {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
        {"$ref": "#/definitions/x.com.st.mediaPreset"}
      ],
      "required": ["presets"]
    }
- PresetUpdate: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.mediaPreset.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description" : "Copyright (c) 2016, 2017 Open Connectivity Foundation, Inc. All rights reserved.",
      "title": "WWST Mode Update",
      "definitions": {
        "x.com.st.mediaPreset": {
          "type": "object",
          "properties": {
            "presetId": {
              "type": "object",
              "readOnly": true,
              "description": "Id of the preset to be played",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
        {"$ref": "#/definitions/x.com.st.mediaPreset"}
      ],
      "required": ["presetId"]
    }

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a","oic.if.s","oic.if.baseline"]

/WWSTMediaPresetResURI:
  description: |
      Allows setting a preset from a know list of presets for the media player
  displayName: WWST Media Preset
  is: [ interface ]

  get:
    description: |
       Array of all the presets for the player. It's containing 'id' and 'name' as mandatory fields.
    responses:
      200:
        body:
          application/json:
            schema: Presets
            example: |
              {
                "rt": ["x.com.st.mediaPreset"],
                "id": "unique_example_id",
                "presets": [
                  {
                    "id": "some example ID",
                    "name": "some example preset name"
                  }
                ]
              }

  post:
    description: |
      Sets a preset from a list of presets for the media player
    body:
      application/json:
        schema: PresetUpdate
        example: |
          {
            "id":    "unique_example_id",
            "presetId": "some example ID"
          }
    responses:
      200:
        body:
          application/json:
            schema: PresetUpdate
            example: |
              {
                "id":    "unique_example_id",
                "presetId": "some example ID"
              }

      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an value for presetId that is not found in presets.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: PresetUpdate
            example: |
              {
                "id": "unique_example_id",
                "presetId": "some example ID",
                "presets": [
                  {
                    "id": "other example ID",
                    "name": "some example preset name"
                  }
                ]
              }
