#%RAML 0.8
title: WWST bodyMassIndexMeasurement
version: v1.0.0-20180807
schemas:
- BodyMassIndexMeasurement: |
    {
        "id": "http://www.samsung.com/schemas/x.com.st.bodyMassIndexMeasurement.json#",
        "$schema": "http://json-schema.org/draft-04/schema#",
        "description" : "Copyright (c) 2016, 2017, 2018 Open Connectivity Foundation, Inc. All rights reserved.",
        "definitions": {
            "x.com.st.bodyMassIndexMeasurement": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "number",
                        "description": "The body mass index of an individual as expressed in kg/m<sup>2</sup>"
                    }
                }
            }
        },
        "type": "object",
        "allOf": [
            {
                "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
            },
            {
                "$ref": "#/definitions/x.com.st.bodyMassIndexMeasurement"
            }
        ],
        "required": [
            "value"
        ]
    }

traits:
    - interface:
        queryParameters:
            if:
                enum: ["oic.if.s","oic.if.baseline"]

/WWSTBMIResURI:
    description: |
        The body mass index of an individual
    displayName: WWST Body Mass Index Measurement
    is: [ interface ]

    get:
        description: |
            Retrieves the body mass index of an individual
        responses:
            200:
                body:
                    application/json:
                        schema: BodyMassIndexMeasurement
                        example: |
                            {
                                "rt": ["x.com.st.bodyMassIndexMeasurement"],
                                "id": "unique_example_id",
                                "value": 20.3
                            }